#!/usr/bin/env php
<?php
require_once __DIR__ . DIRECTORY_SEPARATOR . "AutoLoader.php";

$server = \BrickLayer\Lay\Core\LayConfig::server_data();
$root = $server->root;
$temp = $server->temp;
$command = file_exists($root . "composer.lock") ? "update" : "install";

exec("export HOME=$root && cd $root && composer $command --no-dev --optimize-autoloader 2>&1", $out);

file_put_contents($temp . "deploy_composer_output.txt", implode("\n", $out));

// unset cron job after updating composer packages
\BrickLayer\Lay\Libs\LayCron::new()->unset("update-composer-pkgs");
