#!/usr/bin/env php
<?php

if(!defined("SAFE_TO_INIT_LAY"))
    define("SAFE_TO_INIT_LAY", true);

include_once __DIR__ . DIRECTORY_SEPARATOR . "foundation.php";

new \BrickLayer\Lay\BobDBuilder\Engine($argv);
